# Generated by Django 4.1.7 on 2023-07-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="pages",
            field=models.IntegerField(default=0),
        ),
    ]
