# Generated by Django 4.1.7 on 2023-07-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0002_book_description_book_pages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-updated"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["-updated"]},
        ),
        migrations.AddField(
            model_name="book",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="category",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
