# Generated by Django 4.1.7 on 2023-07-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0004_book_created_category_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
